### ISSUE TITLE
8.1.0系统，java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by vivian2011** [PAGalaxyLab/YAHFA#84]
android 8.1.0系统 出现错误，8.1.0以下版本没有错误
错误信息：
12-04 16:28:54.988 15820-15820/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: lab.galaxy.yahfa.demoApp, PID: 15820
    java.lang.NoSuchMethodError: No static method backup(Ljava/lang/String;Ljava/lang/String;)I in class LdemoPlugin/Hook_Log_e; or its super classes (declaration of 'demoPlugin.Hook_Log_e' appears in /data/app/lab.galaxy.yahfa.demoApp--hpftAuBJPiflpVPasa-WA==/base.apk!classes2.dex)
        at demoPlugin.Hook_Log_e.hook(Hook_Log_e.java:15)
        at lab.galaxy.yahfa.HookMain.doHookItemDefault(HookMain.java:77)
        at lab.galaxy.yahfa.HookMain.doHookDefault(HookMain.java:38)
        at lab.galaxy.yahfa.demoApp.MainApp.attachBaseContext(MainApp.java:28)
        at android.app.Application.attach(Application.java:198)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1047)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6138)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7014)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)

**Comment by vivian2011** [comment]
补充下
originMethod is at 0x71323ff8, hook method is at 0xe66e1d8c, backup method is at 0x0

**Comment by rk700** [comment]
找了台8.1的一加6，没有出现你的问题

可以再用library中的HookingTest测试下

**Comment by rk700** [comment]
可以再试下最新版本，修复了某些情况下8.1系统backup方法未找到的问题 https://github.com/rk700/YAHFA/commit/632342d04b29f91b4cc4bf03d60e72ecf50ff860
