### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by vivian2011** [PAGalaxyLab/YAHFA#85]
java.lang.IllegalArgumentException: Incompatible argument #0: Backup: class java.lang.Object, Original: class lab.galaxy.yahfa.demoApp.ClassWithVirtualMethod
        at lab.galaxy.yahfa.HookMain.checkCompatibleMethods(HookMain.java:169)
        at lab.galaxy.yahfa.HookMain.backupAndHook(HookMain.java:119)
12-04 14:17:31.905 23580-23580/? W/System.err:     at lab.galaxy.yahfa.HookMain.findAndBackupAndHook(HookMain.java:98)
        at lab.galaxy.yahfa.HookMain.doHookItemDefault(HookMain.java:85)
        at lab.galaxy.yahfa.HookMain.doHookDefault(HookMain.java:38)
12-04 14:17:31.906 23580-23580/? W/System.err:     at lab.galaxy.yahfa.demoApp.MainApp.attachBaseContext(MainApp.java:28)
        at android.app.Application.attach(Application.java:196)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
        at android.app.Instrumentation.newApplication(Instrumentation.java:993)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5611)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)

checkCompatibleMethods(target, hook, "Original", "Hook");通过
checkCompatibleMethods(backup, hook, "Backup", "hook");通过
checkCompatibleMethods(backup, target, "Backup", "Original");报错了

**Comment by rk700** [comment]
在 https://github.com/rk700/YAHFA/commit/f95b323c96a7d862a1e48be9921b1d248e052d97 中放松了对backup的检查
